---
abstract: 'Builds and installs the V8 JavaScript engine'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-V8
provides:
  Alien::V8:
    file: lib/Alien/V8.pm
    version: '0.04'
requires:
  Archive::Tar: '1.38'
  File::ShareDir: '1.00'
  IPC::Cmd: '0.42'
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
